Categorization
joona0825/winterstudy pull request #1
Opened 2021-01-08 08:21 UTC by sejkimm

### **0. Categorization**

### **1. Add Route /category** 
**1.1 Add /html/CategoryList.html**
-  It renders /category

**1.2 Add func _ListCategory() in (app.go)**
- It controls /html/CategoryList.html

**1.3 Add func _getCategoryList() in (dataprocess.go)**
- Get category list form DB and returns to _ListCategory()

### **2. add Route /category/{cat}** 
**2.1 Add /html/Category.html**
-  It renders /category/{cat}. It is similar with /html/index.html but it does not cotain paging and submit code href.

**2.2 Add func _getCategoryCode() in (app.go)**
- It controls /html/Category.html

**2.3 Add func _getPostListFromCategory() in (dataprocess.go)**
- Get posts from DB and returns to _getCategoryCode(). It is similar with _getPostList() in dataprocess.go but it returns specific code from DB that matches category.

### **3. modify DB Scheme**
Check Line19~32 in dataprocess.go

### **Things to check meticulously**
- function _ListCategory in (app.go), Line 163~167. 
- /html/categorylist.html, Line 25~27.

2021-01-08 08:53 UTC, joona0825 commented on app.go
> +	if err == nil {
Variable err is not declared here

2021-01-08 09:01 UTC, joona0825 requested changes

2021-01-08 09:01 UTC, hellojunha commented on app.go
> +	if err == nil {
Variable err is not declared

2021-01-08 09:01 UTC, hellojunha commented on app.go
> +	list = getPostListFromCategory(cat)
No pagination needed?

2021-01-08 09:01 UTC, hellojunha commented on app.go
> +		t, err := template.ParseFiles(wd + "/html/categoryList.html")
Method for getting template file has changed. Check out the latest commit.

2021-01-08 09:01 UTC, hellojunha commented on app.go
> +	t, err := template.ParseFiles(wd + "/html/index.html")
Method for getting template file has changed. Check out the latest commit.

2021-01-08 09:01 UTC, hellojunha commented on html/post.html
> +        <option value="LinkedList">LinkedList</option>
hard code?

2021-01-08 09:01 UTC, hellojunha commented on dataprocess.go
> +	Category []Category // Add relationship in DB
Why array?

2021-01-08 09:01 UTC, hellojunha commented on dataprocess.go
> +			err := rows.Scan(&category)
Variable category is not declared

2021-01-08 09:01 UTC, hellojunha commented on dataprocess.go
> +func getPostListFromCategory(string cat) [] {
return type?

2021-01-08 09:05 UTC, joona0825 commented
Please upload sql query I need to execute (study_category table). And you don't need too much comments in code as you wrote. I personally do not prefer writing comment because it means the code is hard to read and understand.

2021-01-13 13:39 UTC, sejkimm commented on app.go
> +	if err == nil {
Fixed in App.go Line 161, Commit d3e72a5

2021-01-13 13:41 UTC, sejkimm commented on app.go
> +	list = getPostListFromCategory(cat)
All categories have fewer than 10 posts.

2021-01-13 13:41 UTC, sejkimm commented on app.go
> +		t, err := template.ParseFiles(wd + "/html/categoryList.html")
Fixed

2021-01-13 13:41 UTC, sejkimm commented on app.go
> +	t, err := template.ParseFiles(wd + "/html/index.html")
Fixed

2021-01-13 13:41 UTC, sejkimm commented on html/post.html
> +        <option value="LinkedList">LinkedList</option>
Fixed

2021-01-13 13:42 UTC, sejkimm commented on dataprocess.go
> +	Category []Category // Add relationship in DB
Fixed. Now string

2021-01-13 13:42 UTC, sejkimm commented on dataprocess.go
> +			err := rows.Scan(&category)
Fixed

2021-01-13 13:42 UTC, sejkimm commented on dataprocess.go
> +func getPostListFromCategory(string cat) [] {
Fixed

2021-01-13 13:48 UTC, sejkimm commented
Thanks for your review. 
I fixed several errors and It now works properly on my local environment.

SQL query for my commit is below 
`CREATE TABLE study_category ( category_id INT(11) NOT NULL AUTO_INCREMENT, category TINYTEXT NOT NULL, Week INT(11) NOT NULL, PRIMARY KEY(category_id));`

and might need one more query 
`ALTER TABLE study_post ADD COLUMN category TINYTEXT NOT NULL`

Also I removed every comment I wrote.

2021-01-13 13:58 UTC, merged